# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"7\n\x10OperationRequest\x12\x10\n\x08\x66irstArg\x18\x01 \x01(\x02\x12\x11\n\tsecondArg\x18\x02 \x01(\x02\"C\n\x11OperationResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x02\x32\xe4\x01\n\x11\x43\x61lculatorService\x12\x32\n\tAddValues\x12\x11.OperationRequest\x1a\x12.OperationResponse\x12\x32\n\tSubValues\x12\x11.OperationRequest\x1a\x12.OperationResponse\x12\x33\n\nMultValues\x12\x11.OperationRequest\x1a\x12.OperationResponse\x12\x32\n\tDivValues\x12\x11.OperationRequest\x1a\x12.OperationResponseb\x06proto3')



_OPERATIONREQUEST = DESCRIPTOR.message_types_by_name['OperationRequest']
_OPERATIONRESPONSE = DESCRIPTOR.message_types_by_name['OperationResponse']
OperationRequest = _reflection.GeneratedProtocolMessageType('OperationRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:OperationRequest)
  })
_sym_db.RegisterMessage(OperationRequest)

OperationResponse = _reflection.GeneratedProtocolMessageType('OperationResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:OperationResponse)
  })
_sym_db.RegisterMessage(OperationResponse)

_CALCULATORSERVICE = DESCRIPTOR.services_by_name['CalculatorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATIONREQUEST._serialized_start=20
  _OPERATIONREQUEST._serialized_end=75
  _OPERATIONRESPONSE._serialized_start=77
  _OPERATIONRESPONSE._serialized_end=144
  _CALCULATORSERVICE._serialized_start=147
  _CALCULATORSERVICE._serialized_end=375
# @@protoc_insertion_point(module_scope)
